FROM circleci/node:14-browsers

USER root
# Install common user folders espically the `Downloads` folder
RUN sudo apt-get install xdg-user-dirs

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn
